export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Problem } from './Problem';
export { default as HowItWorks } from './HowItWorks';
export { default as Features } from './Features';
export { default as Integrations } from './Integrations';
export { default as CTA } from './CTA';
export { default as Footer } from './Footer';
export { default as Pricing } from './Pricing';
